name: "Deploy"
description: "Deploy Code"
inputs:
  environment:
    description: 'enviroment for testing'
    required: true
  port:
    description: 'port to deploy'
    required: true

runs:
  using: composite
  steps:


    - name: Print step name
      run: echo "Acessing repository"
      shell: cmd

    - uses: actions/checkout@v4
      with:
        repository: 'mtararujs/python-greetings'
        path: ./python-greetings

    - name: Check variables..
      run: echo "${{inputs.environment}}, ${{inputs.port}}"
      shell: cmd
      working-directory: ./python-greetings

    - name: Checking folder
      run: dir
      shell: cmd
      working-directory: ./python-greetings

    - name: Deleting Existing Processes
      run: pm2 delete greetings-app-${{inputs.environment}} & EXIT /B 0
      shell: cmd
      working-directory: ./python-greetings

    - name: Run pm2 process..
      run: pm2 start app.py --name greetings-app-${{inputs.environment}} --watch -- --port ${{inputs.port}}
      shell: cmd
      working-directory: ./python-greetings

