name: "Deploy"
description: "Deploy Code"
inputs:
  environment:
    description: 'enviroment for testing'
    required: true
  port:
    description: 'port to deploy'
    required: true

runs:
  using: composite
  steps:


    - name: Print step name
      run: echo "Acessing repository"
      shell: cmd

    - uses: actions/checkout@v4
      with:
        repository: 'mtararujs/python-greetings'
        path: ./deploy/

    - name: Print step name
      run: echo "${{inputs.environment}}, ${{inputs.port}}"
      shell: cmd
      working-directory: ./deploy

    - name: Print step name
      run: echo "Checking folder"
      shell: cmd
      working-directory: ./deploy

    - name: Print step name
      run: dir
      shell: cmd
      working-directory: ./deploy

    - name: Print step name
      run: echo "Deleting Existing Processes"
      shell: cmd
      working-directory: ./deploy

    - name: Print step name
      run: pm2 delete greetings-app-${{inputs.environment}} & EXIT /B 0
      shell: cmd
      working-directory: ./deploy

    - name: Print step name
      run: echo "Run pm2 process.."
      shell: cmd
      working-directory: ./deploy

    - name: Print step name
      run: pm2 start app.py --name greetings-app-${{inputs.environment}} -- --port ${{inputs.port}}
      shell: cmd
      working-directory: ./deploy

