name: "Install"
description: "Install dependencies"

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        repository: 'n1ckyg/python-greetings'
    - name: Print step name
      run: echo "Acessing repository"
      shell: cmd
    - name: Print step name
      run: echo "Checking folder"
      shell: cmd
    - name: Print step name
      run: echo "dir"
      shell: cmd
    - name: Print step name
      run: echo "Installing Python"
      shell: cmd
    - name: Print step name
      run: echo "pip install -r requirements.txt"
      shell: cmd
    