name: Praktiskais Darbs Github Actions

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  install-pip-deps:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install

  deploy-to-dev:
    runs-on: self-hosted
    needs: [install-pip-deps]
    steps:
      - name: test
        run: echo "Deploying to dev"

  tests-on-dev:
    runs-on: self-hosted
    needs: [deploy-to-dev]
    steps:
      - name: test
        run: echo "Testing on dev"

  deploy-to-staging:
    runs-on: self-hosted
    needs: [tests-on-dev]
    steps:
      - name: test
        run: echo "Deploying to staging"

  tests-on-staging:
    runs-on: self-hosted
    needs: [deploy-to-staging]
    steps:
      - name: test
        run: echo "Testing on staging"

  deploy-to-preprod:
    runs-on: self-hosted
    needs: [tests-on-staging]
    steps:
      - name: test
        run: echo "Deploying to preprod"

  tests-on-preprod:
    runs-on: self-hosted
    needs: [deploy-to-preprod]
    steps:
      - name: test
        run: echo "Testing on preprod"

  deploy-to-prod:
    runs-on: self-hosted
    needs: [tests-on-preprod]
    steps:
      - name: test
        run: echo "Deploying to prod"

  tests-on-prod:
    runs-on: self-hosted
    needs: [deploy-to-prod]
    steps:
      - name: test
        run: echo "Testing on prod"
