name: Praktiskais Darbs Github Actions

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  install-pip-deps:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install

  deploy-to-dev:
    runs-on: self-hosted
    needs: [install-pip-deps]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy
        with:
          environment: 'dev'
          port: '7001'



  tests-on-dev:
    runs-on: self-hosted
    needs: [deploy-to-dev]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test
        with:
          environment: 'dev'
          test-suite: 'greetings'

  deploy-to-staging:
    runs-on: self-hosted
    needs: [tests-on-dev]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy
        with:
          environment: 'staging'
          port: '7002'

  tests-on-staging:
    runs-on: self-hosted
    needs: [deploy-to-staging]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test
        with:
          environment: 'staging'
          test-suite: 'greetings'

  deploy-to-preprod:
    runs-on: self-hosted
    needs: [tests-on-staging]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy
        with:
          environment: 'preprod'
          port: '7003'

  tests-on-preprod:
    runs-on: self-hosted
    needs: [deploy-to-preprod]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test
        with:
          environment: 'preprod'
          test-suite: 'greetings'

  deploy-to-prod:
    runs-on: self-hosted
    needs: [tests-on-preprod]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy
        with:
          environment: 'prod'
          port: '7004'

  tests-on-prod:
    runs-on: self-hosted
    needs: [deploy-to-prod]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test
        with:
          environment: 'prod'
          test-suite: 'greetings'
      